══════════════════════ Running solver against test cases ══════════════════════
=> base:[cases.tio(07)] prog:[solver.py] [ϵ ω ω ✓ ω ω ✓]
(ϵ execution)[00] GR:014 cases.tio (duas raízes) 
(ω wrong_out)[01] GR:014 cases.tio (duas raízes) 
(ω wrong_out)[02] GR:014 cases.tio (uma raiz   ) 
(✓ correct__)[03] GR:014 cases.tio (sem raízes ) 
(ω wrong_out)[04] GR:014 cases.tio (05         ) 
(ω wrong_out)[05] GR:014 cases.tio (06         ) 
(✓ correct__)[06] GR:014 cases.tio (07         ) 
╭──────────────────────────────────────────────────────────────────────────────
│              (ϵ execution)[00] GR:014 cases.tio (duas raízes)                
├─────────────────────────────────── INPUT ────────────────────────────────────
├────────────────────────────────── EXPECTED ──────────────────────────────────
│ 0.44
│ -5.07
│ 
│ 
│ 
├────────────────────────────────── RECEIVED ──────────────────────────────────
│ Traceback (most recent call last):
│   File "/home/sena/Dropbox/gits/tools/tko/ihc_tests/03_run/fup_001/./solver.py", line 1, in <module>
│     a = float(input())
│               ^^^^^^^
│ EOFError: EOF when reading a line
╰──────────────────────────────────────────────────────────────────────────────

