#!/bin/bash

tko -m run exception.py
